backend:
  name: github
  repo: ntrossat/voguemerry # Path to your Github repository
  branch: master # Branch to update
media_folder: "static/images/cms" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/cms" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Type", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Brouillon", name: "draft", widget: "string"}
      - {label: "Date de publication", name: "date", widget: "datetime"}
      - {label: "Image principale", name: "image", widget: "image"}
      - {label: "Vidéo Youtube", name: "video", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
